version: "2.1"
services:

  server:
    image: 'screeps'
    restart: always
    depends_on:
      - mongo
      - redis 
    environment:
      - STEAM_KEY=''
    volumes:
      - '~/screeps:/screeps'
    ports: 
      - 21025:21025

  mongo:
    image: ivanmarban/armhf-mongodb
    restart: always
    volumes:
      - '~/mongo:/var/lib/mongodb'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:27017"]
        interval: 30s
        timeout: 10s
        retries: 5

  redis:
    image: redis
    restart: always
    volumes:
      - '~/redis:/data'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:6379"]
        interval: 30s
        timeout: 10s
        retries: 5
